### ISSUE TITLE
リマインドの方式を考える

### ISSUE THREAD

**Issue by pyama86** [pepabo/collec#2]
Cronでやるか、Sidekiqでやるか。個人的にはSidekiqでとりあえずキューイングしちゃって、キュー処理するときにその人が処理済みか、未処理か見て、未処理だったらリマインド、未処理だったらリマインドしてエンキューとかでいいんじゃないかなと思っている。

ただその場合、Redisかmysqlでキュー管理しないと行けないのでそれがちょいダル。
他になにかアイディアあればあれをあれください。

**Comment by hypermkt** [comment]
自分もSidekiq案で良いかと思いました。が、他に無いか調査検討してみます。

**Comment by takumakume** [comment]
もともとファイルベースとcronで頑張る、、と思ったけど
やはりsidekiqの方が良さそうだと思いました！

**Comment by takumakume** [comment]
以下を参照しながら、リマインド機構を作る

- [Active Job の基礎](https://railsguides.jp/active_job_basics.html)
- [Rails5 + ActiveJob + SidekiqをHerokuで動かす方法](http://qiita.com/kaorumori/items/5571e98759b4275e170d)

**Comment by takumakume** [comment]
リマインド時は例えば以下のようなメッセージを送るかなと思っている。

```
Please check it
https://pepabo.slack.com/archives/D1DFG51A8/p1502527559915899
```

このSlackのリンクは依頼メッセージをAnswerからSlackのAPIを使って送信したメッセージのURLになる。
リマインドを受けた人は以下のように見えるので対応がしやすくなる。

![image](https://user-images.githubusercontent.com/10905048/29239335-3713819e-7f87-11e7-8272-90ab608015e5.png)

そこで必要になるのが、URLの構成要素である以下

- ドメイン: pepabo.slack.com
- SlackのID: C6CF3P6LQ
- 送信時刻: 1502526080800841

送信時刻については、メッセージ送信時に保持しておかなければ再取得はできなさそうなので `chat.postMessage` を実施したタイミングでレスポンスの `ts` を所得しておく必要がありそうだった。


https://api.slack.com/methods/chat.postMessage
```
{
    "ok": true,
    "ts": "1405895017.000506",
    "channel": "C024BE91L",
    "message": {
        ...
    }
}
```

`mentions` テーブルにカラムを追加したほうが良さそうだった。

**Comment by takumakume** [comment]
リマインドでURLを送る前提の話となるけど、
mentionsで "ts" を保持するのではなく、メッセージURLを組み立ててそれを保持した方がよいかな。

**Comment by hypermkt** [comment]
> リマインド時は例えば以下のようなメッセージを送るかなと思っている。

なるほど、そういった方法もありますね！

* メリットとしては、最初のメッセージを生かすことができる。
* デメリットとしては、回答するために前回のメッセージURLを１回クリックする手間があることでしょうか。

または別案としては、同じDMを再送信するのもありかと思いましたが、どうでしょうか？

* メリットしては、すぐに回答ができる
* デメリットとしては、再送信したメッセージ、前回送信したメッセージの２つが存在するので、どちらから回答してもいいようの調整が必要。または前回のメッセージをリマインド前に削除しておくなど実装の手間が増える。

**Comment by takumakume** [comment]
> または別案としては、同じDMを再送信するのもありかと思いましたが、どうでしょうか？

確かに、パラメータを同じにしておけば、再送でもその旨が分かれば良いですね...!!
それが良さそうです！

**Comment by tnmt** [comment]
リマインダの機能自体は出来てるのでClose
