### ISSUE TITLE
herokuボタンの仕様を調べる

### ISSUE THREAD

**Issue by pyama86** [pepabo/collec#3]
当日ハマると一日終わりそうなので、当日までにデプロイ出来るくらいまでは言っときたい。

**Comment by takumakume** [comment]
https://github.com/honeymoon-answer/answer/pull/28
このPRで仮実装して、動作を確認する。

**Comment by takumakume** [comment]
ボタンは以下を記述

```
[![Heroku Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/honeymoon-answer/answer)
```

[![Heroku Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/honeymoon-answer/answer)

こんな感じでデプロイがめ画面を出すことができた。

![image](https://user-images.githubusercontent.com/10905048/29214055-ce95517a-7ee0-11e7-850d-5a75484493f3.png)

仮で入れたロゴ画像が出ていないので修正は必要そう。

Herokuボタンを実装するにあたってやる必要があること

- [ ] アプリのdiscriptionを考える
- [ ] 何かしらのロゴを作成する
