### ISSUE TITLE
雑談用

### ISSUE THREAD

**Issue by pyama86** [pepabo/collec#4]
思いついたことを書く場所

**Comment by pyama86** [comment]
slackはrubyクライアントあった

https://github.com/slack-ruby/slack-ruby-client

あと、チャンネル情報とかいちいち都度取ってられないからキャッシュがいるな。RedisかMemcache。

**Comment by pyama86** [comment]
db、heroku使うなら最初からpostgresqlがいいな。

**Comment by hypermkt** [comment]
プレゼン資料を元に要件を整理してみました📝 。記憶を辿りながら書いているのでどこか間違ってるかも。自由に加筆修正しちゃってください。 

## 用語
* アンケートメッセージ
    * アンケートの登録が完了した際に、指定チャンネルで投稿されたメッセージ

## 要件

### ユーザー
* Slack認証を利用したユーザー登録ができる
    * 指定されたSlackチームしかユーザー登録は出来ない
* ログインできる

### アンケート
* アンケートの登録ができる
    * 以下項目が登録できる
        * 本文
        * Slackチャンネル
        * メンション先 Slackユーザー又はグループ
        * リマインド間隔 (後で資料を確認する)
    * アンケートを登録すると、指定のSlackチャンネルで本文とメンション先が書かれたメッセージがコメントされる。
* アンケートの編集・削除ができる
* アンケートの一覧が表示できる

### アンケートメッセージ
* アンケートメッセージには、本文・メンション先・完了ボタンが表示される
    * ボタン名は「完了」ボタン固定である
* メンションを受けたユーザーは、本文のタスクが完了している場合は完了ボタンを押す
    * 【疑問】SlackのMessage Buttonは複数人のに対応しているのかな？
* メンションを受けたユーザーが完了ボタンを押さなかった場合、アンケート登録された日付を基準に指定されたリマインド間隔で、DMにより通知が行く

**Comment by hypermkt** [comment]
先日共有したSlack Interactive Messageの資料はここに公開しました。Message Buttonを使う際の参考になれば。

[Slack Interactive Messageリファレンス \- Qiita](http://qiita.com/hypermkt/items/b2ffaf610ac92235c4d6)
