### ISSUE TITLE
依頼作成時のグループメンション対応

### ISSUE THREAD

**Issue by hypermkt** [pepabo/collec#89]
以下のようにグループメンションで依頼のDMが送信できるようにしたい。社内品評会で要望も多かったので進めよう！

![image](https://user-images.githubusercontent.com/1726225/30408642-32a49e36-993b-11e7-8087-e74e3da06c69.png)

**Comment by hypermkt** [comment]
`@team-members`の事をSlack用語で[ユーザーグループ](https://get.slack.help/hc/ja/articles/212906697-%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97)と呼ぶ。

**Comment by hypermkt** [comment]
ユーザーグループ一覧は[usergroups.list](https://api.slack.com/methods/usergroups.list)メソッドで取得できる。Testerで確認したけど、結果の配列の中にはユーザーグループに紐づくユーザー一覧は含まれていなかった。

**Comment by hypermkt** [comment]
ユーザーグループ一覧で取得したユーザーグループIDを利用して、ユーザーグループのユーザー一覧は[usergroups.users.list](https://api.slack.com/methods/usergroups.users.list)で取得できる。

**Comment by pyama86** [comment]
やった。
